[main]
namespace=fuzzel
font=Adwaita Sans
#icon-theme=Colloid-Dark
prompt="> "
terminal=foot -a '{cmd}' -T '{cmd}' {cmd}
lines=6
hide-prompt=no
width=50
horizontal-pad=40
vertical-pad=20
line-height=30
enable-mouse=no

anchor=center

[colors]
background=343437FF
text=FFFFFFFF
message=FFFFFFFF
prompt=FFFFFFFF
placeholder=FFFFFFFF
input=FFFFFFFF
match=81D0FFFF
selection=FFFFFF08
selection-text=FFFFFFFF
selection-match=81D0FFFF
counter=93a1a1ff
border=002b36ff

[border]
width=0
radius=12
selection-radius=4
