# fuzzel configuration file
# ~/.config/fuzzel/fuzzel.ini

[main]
#include=
namespace=fuzzel
#output=
font=Adwaita Sans
#use-bold=yes
#dpi-aware=auto
#gamma-correct=no
#placeholder=
prompt=">>> "
#message=
#message-mode=wrap
#icon-theme=default
#icons-enabled=yes
#hide-before-typing=no
#fields=filename,name,generic
#password-character=*
#match-mode=fzf
#sort-result=yes
#match-counter=no
#filter-desktop=no
#show-actions=no
terminal=foot -a '{cmd}' -T '{cmd}' {cmd}
#list-executables-in-path=no
#launch-prefix=
#anchor=center
#x-margin=0
#y-margin=0
lines=8
hide-prompt=yes
#minimal-lines=no
width=50
#tabs=8
horizontal-pad=40
vertical-pad=20
#inner-pad=0
#image-size-ratio=0.5
line-height=30
#letter-spacing=
#layer=overlay
#keyboard-focus=exclusive
#exit-on-keyboard-focus-loss=yes
#render-workers=       # default: number of logical CPUs
#match-workers=        # default: number of logical CPUs
#delayed-filter-ms=300
#delayed-filter-limit=20000
#scaling-filter=box
#cache=                # default: $XDG_CACHE_HOME/fuzzel
#auto-select=no
enable-mouse=no

[colors]
background=343437ff
text=ffffffff
#message=657b83ff
#prompt=586e75ff
#placeholder=93a1a1ff
#input=657b83ff
#match=cb4b16ff
selection=#ffffff08
selection-text=ffffffff
selection-match=ffffffff
#counter=93a1a1ff
#border=002b36ff

[border]
width=0
radius=12
selection-radius=4

[dmenu]
#mode=text
#exit-immediately-if-empty=no

[key-bindings]
#cancel=Control+g Control+c Control+bracketleft Escape
#execute=Return KP_Enter Control+y
#execute-or-next=Tab
#execute-input=Shift+Return Shift+KP_Enter
#cursor-left=Left Control+b
#cursor-left-word=Control+Left Mod1+b
#cursor-right=Right Control+f
#cursor-right-word=Control+Right Mod1+f
#cursor-home=Home Control+a
#cursor-end=End Control+e
#delete-line-backward=Control+u
#delete-line-forward=Control+k
#delete-line=Control+Shift+BackSpace
#delete-prev=BackSpace Control+h
#delete-prev-word=Mod1+BackSpace Control+BackSpace Control+w
#delete-next=Delete
#delete-next-word=Mod1+d Control+Delete
#insert-selected=Control+Tab
#expunge=Shift+Delete
#clipboard-paste=Control+v XF86Paste
#primary-paste=Shift+Insert Shift+KP_Insert
#prev=Up Control+p
#prev-with-wrap=ISO_Left_Tab
#prev-page=PageUp KP_PageUp
#next=Down Control+n
#next-with-wrap=none
#next-page=Page_Down KP_Page_Down
#first=Control+Home
#last=Control+End
#custom-1=Mod1+1
#custom-2=Mod1+2
#custom-3=Mod1+3
#custom-4=Mod1+4
#custom-5=Mod1+5
#custom-6=Mod1+6
#custom-7=Mod1+7
#custom-8=Mod1+8
#custom-9=Mod1+9
#custom-10=Mod1+10
#custom-11=Mod1+11
#custom-12=Mod1+12
#custom-13=Mod1+13
#custom-14=Mod1+14
#custom-15=Mod1+15
#custom-16=Mod1+16
#custom-17=Mod1+17
#custom-18=Mod1+18
#custom-19=Mod1+19
