# DARK-MODE

[main]
namespace=fuzzel
font=Adwaita Sans
prompt=">>> "
terminal=foot -a '{cmd}' -T '{cmd}' {cmd}
lines=6
hide-prompt=yes
width=50
horizontal-pad=40
vertical-pad=20
line-height=30
enable-mouse=no

[colors]
background=343437FF
text=FFFFFFFF
match=81D0FFFF
selection=FFFFFF08
selection-text=FFFFFFFF
selection-match=81D0FFFF

[border]
width=0
radius=12
selection-radius=4
