# -*- conf -*-

# shell=$SHELL (if set, otherwise user's default shell from /etc/passwd)
# term=foot (or xterm-256color if built with -Dterminfo=disabled)
# login-shell=no

# app-id=foot # globally set wayland app-id. Default values are "foot" and "footclient" for desktop and server mode
# title=foot
# locked-title=no

font=MonaspiceArNerdFontMono:size=18
pad=32x32 center-when-maximized-and-fullscreen

[colors-dark]
alpha=0.8
foreground=dfdfe0
background=292a30
regular0=414453
regular1=ff8170
regular2=78c2b3
regular3=d9c97c
regular4=4eb0cc
regular5=ff7ab2
regular6=b281eb
regular7=dfdfe0
bright0=7f8c98
bright1=ff8170
bright2=acf2e4
bright3=ffa14f
bright4=6bdfff
bright5=ff7ab2
bright6=dabaff
bright7=dfdfe0
selection-foreground=dfdfe0
selection-background=414453
